# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_nested.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_nested.proto',
  package='',
  serialized_pb=_b('\n\x10\x63\x61r_nested.proto\"8\n\tCarNested\x12\x19\n\x02id\x18\x01 \x02(\x0b\x32\r.CarNested.Id\x1a\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CARNESTED_ID = _descriptor.Descriptor(
  name='Id',
  full_name='CarNested.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CarNested.Id.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=76,
)

_CARNESTED = _descriptor.Descriptor(
  name='CarNested',
  full_name='CarNested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CarNested.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CARNESTED_ID, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=76,
)

_CARNESTED_ID.containing_type = _CARNESTED
_CARNESTED.fields_by_name['id'].message_type = _CARNESTED_ID
DESCRIPTOR.message_types_by_name['CarNested'] = _CARNESTED

CarNested = _reflection.GeneratedProtocolMessageType('CarNested', (_message.Message,), dict(

  Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
    DESCRIPTOR = _CARNESTED_ID,
    __module__ = 'car_nested_pb2'
    # @@protoc_insertion_point(class_scope:CarNested.Id)
    ))
  ,
  DESCRIPTOR = _CARNESTED,
  __module__ = 'car_nested_pb2'
  # @@protoc_insertion_point(class_scope:CarNested)
  ))
_sym_db.RegisterMessage(CarNested)
_sym_db.RegisterMessage(CarNested.Id)


# @@protoc_insertion_point(module_scope)
