# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_repeat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_repeat.proto',
  package='',
  serialized_pb=_b('\n\x10\x63\x61r_repeat.proto\"2\n\tCarRepeat\x12\x17\n\x05seats\x18\x01 \x03(\x0b\x32\x08.CarSeat\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x18\n\x07\x43\x61rSeat\x12\r\n\x05\x63olor\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CARREPEAT = _descriptor.Descriptor(
  name='CarRepeat',
  full_name='CarRepeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seats', full_name='CarRepeat.seats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='CarRepeat.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=70,
)


_CARSEAT = _descriptor.Descriptor(
  name='CarSeat',
  full_name='CarSeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='CarSeat.color', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=96,
)

_CARREPEAT.fields_by_name['seats'].message_type = _CARSEAT
DESCRIPTOR.message_types_by_name['CarRepeat'] = _CARREPEAT
DESCRIPTOR.message_types_by_name['CarSeat'] = _CARSEAT

CarRepeat = _reflection.GeneratedProtocolMessageType('CarRepeat', (_message.Message,), dict(
  DESCRIPTOR = _CARREPEAT,
  __module__ = 'car_repeat_pb2'
  # @@protoc_insertion_point(class_scope:CarRepeat)
  ))
_sym_db.RegisterMessage(CarRepeat)

CarSeat = _reflection.GeneratedProtocolMessageType('CarSeat', (_message.Message,), dict(
  DESCRIPTOR = _CARSEAT,
  __module__ = 'car_repeat_pb2'
  # @@protoc_insertion_point(class_scope:CarSeat)
  ))
_sym_db.RegisterMessage(CarSeat)


# @@protoc_insertion_point(module_scope)
