# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car.proto',
  package='',
  serialized_pb=_b('\n\tcar.proto\"7\n\x03\x43\x61r\x12\x12\n\nnum_wheels\x18\x01 \x02(\r\x12\r\n\x05\x63olor\x18\x10 \x01(\t\x12\r\n\x05\x62rand\x18\x11 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAR = _descriptor.Descriptor(
  name='Car',
  full_name='Car',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_wheels', full_name='Car.num_wheels', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='Car.color', index=1,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brand', full_name='Car.brand', index=2,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Car'] = _CAR

Car = _reflection.GeneratedProtocolMessageType('Car', (_message.Message,), dict(
  DESCRIPTOR = _CAR,
  __module__ = 'car_pb2'
  # @@protoc_insertion_point(class_scope:Car)
  ))
_sym_db.RegisterMessage(Car)


# @@protoc_insertion_point(module_scope)
